node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/sunnybg111/JWT-Zuul-Docker-Boot-Angulr7-Ribbon.git', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('demo') {
                def app = docker.build "localhost:8080/demo:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:8080/demo${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        }

            

    }

}
